# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '主页面.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import shutil
import sys
import threading
from datetime import datetime

from PyQt5 import QtCore, QtGui, QtWidgets
# import win32clipboard as w
from PyQt5.QtCore import Qt, QCoreApplication, QRect, QMetaObject, QSize, pyqtSignal, QObject
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QTreeWidgetItem, QMenu, QHBoxLayout, QMenuBar, QPushButton, \
    QCheckBox, QStatusBar, QTreeWidget, QWidget, QSplitter, QTabWidget, QScrollArea

from Plugin import Plugin
from msg_deliver import del_plugin
from pluginLaoder import add_plugin_with_win, sql


class MyTypeSignal(QObject):
    # 定义一个信号
    sendmsg = pyqtSignal(dict)
    add_plugin = pyqtSignal(Plugin)



class Message_detail(object):  # 定义消息详情界面
    def __init__(self):
        self.Form = QtWidgets.QWidget()
        # Form.show()
        self.Form.setFixedSize(self.Form.width(), self.Form.height())
        self.Form.setObjectName("Message detail")
        self.Form.setWindowIcon(QIcon('./icons/message.png'))
        self.Form.resize(552, 299)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.Form)
        # self.plainTextEdit.setGeometry(QtCore.QRect(3, 3, 548, 296))
        self.plainTextEdit.setGeometry(QtCore.QRect(3, 3, self.Form.width() - 10, self.Form.height() - 10))
        self.plainTextEdit.setObjectName("plainTextEdit")
        # self.c = Mysignal()
        self.retranslateUi(self.Form)
        QtCore.QMetaObject.connectSlotsByName(self.Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.Form.setWindowTitle(_translate("Message detail", "消息详情"))
        # Form.show()

    def show_ui(self):
        self.Form.show()
        # return

    def set_text(self, s: str):
        self.plainTextEdit.setPlainText(s)




class My_tree_item(QTreeWidgetItem):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.plugin: Plugin = None


class Ui_MainWindow(object):
    # singal = pyqtSignal(dict)
    s = MyTypeSignal()

    def __init__(self):
        self.plugins = []
        self.plu_list = None
        self.mainwindow = None
        self.layout = QHBoxLayout()
        self.logs = []
        # self.plugins = []
        # self.
        self.s.sendmsg.connect(self.addlog)
        self.s.add_plugin.connect(self.addplugin)  # 添加函数
        # self.si

    def addplugin_(self, plu):
        self.plu_list = plu

    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QIcon('./icons/qmiao.png'))
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(733, 303)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1061, 391))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.scrollArea = QScrollArea(self.tab)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 0, 1061, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1059, 359))
        self.splitter = QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(570, 10, 150, 24))
        self.splitter.setOrientation(Qt.Horizontal)
        self.treeWidget_2 = QTreeWidget(self.scrollAreaWidgetContents)
        self.treeWidget_2.setObjectName(u"treeWidget_2")
        self.treeWidget_2.setGeometry(QRect(-5, 1, 731, 231))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        icon = QIcon('./icons/pyd.ico')
        iconThemeName = u"1"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)

        self.tabWidget.addTab(self.tab, icon, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.treeWidget = QTreeWidget(self.tab_2)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(-5, 1, 731, 231))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.checkBox = QCheckBox(self.tab_3)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(20, 20, 321, 141))
        self.pushButton = QPushButton(self.tab_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(590, 170, 101, 41))
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 733, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.treeWidget_2.customContextMenuRequested.connect(self.pluginMenu)
        self.treeWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        self.treeWidget_2.setContextMenuPolicy(Qt.CustomContextMenu)
        self.treeWidget.customContextMenuRequested.connect(self.logMenu)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)
        # self.singal.connect(self.addlog)
        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        ___qtreewidgetitem = self.treeWidget_2.headerItem()
        ___qtreewidgetitem.setText(5, QCoreApplication.translate("MainWindow", u"\u8bf4\u660e", None));
        ___qtreewidgetitem.setText(4, QCoreApplication.translate("MainWindow", u"\u7248\u672c", None));
        ___qtreewidgetitem.setText(3, QCoreApplication.translate("MainWindow", u"\u4f5c\u8005", None));
        ___qtreewidgetitem.setText(2, QCoreApplication.translate("MainWindow", u"\u63d2\u4ef6", None));
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"\u72b6\u6001", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"\u5e8f\u53f7", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab),
                                  QCoreApplication.translate("MainWindow", u"\u63d2\u4ef6\u7ba1\u7406", None))
        ___qtreewidgetitem1 = self.treeWidget.headerItem()
        ___qtreewidgetitem1.setText(4, QCoreApplication.translate("MainWindow", u"\u5185\u5bb9", None));
        ___qtreewidgetitem1.setText(3, QCoreApplication.translate("MainWindow", u"\u53d1\u9001\u8005", None));
        ___qtreewidgetitem1.setText(2, QCoreApplication.translate("MainWindow", u"\u79cd\u7c7b", None));
        ___qtreewidgetitem1.setText(1, QCoreApplication.translate("MainWindow", u"\u65f6\u95f4", None));
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"\u5e8f\u53f7", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2),
                                  QCoreApplication.translate("MainWindow", u"\u65e5\u5fd7", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\u5d29\u6e83\u91cd\u542f", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u8bbe\u7f6e", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3),
                                  QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))

    # retranslateUi

    def logMenu(self, pos):
        menu = QMenu()
        item1 = menu.addAction("删除本条")
        item2 = menu.addAction("复制此条消息")
        item3 = menu.addAction("查看消息详情")
        screenPos = self.treeWidget.mapToGlobal(pos)
        action = menu.exec(screenPos)
        if action == item1:
            if len(self.treeWidget.selectedIndexes()) == 0:
                pass
            else:
                self.treeWidget.takeTopLevelItem(self.treeWidget.selectedIndexes()[0].row())
                return
        elif action == item2:
            if len(self.treeWidget.selectedIndexes()) == 0:
                pass
            else:
                row = self.treeWidget.selectedIndexes()[0].row()  # 列
                # print(row)
                # col = self.treeWidget.selectedIndexes()[0].column()
                # setText(self.logs[row].text(4))
            # print(self.logs[row].text(4))
        elif action == item3:
            if len(self.treeWidget.selectedIndexes()) == 0:
                pass
            else:
                row = self.treeWidget.selectedIndexes()[0].row()  # 列
                # print(self.logs[row].text(4))
                self.show_message(self.logs[row].text(4))

    def addlog(self, dic: dict):
        # os.mkdir(os.getcwd()+'/log/' + datetime.now().strftime("%Y-%m-%d") + '.log')
        # os.chdir('./log')
        # with open('./log/' + datetime.now().strftime("%Y-%m-%d") + '.log', 'w+') as f:
        #     f.write(str(dic) + "\n")
        n = self.treeWidget.topLevelItemCount()
        time_ = datetime.now().strftime("%H:%M:%S")
        root = QTreeWidgetItem(self.treeWidget)
        self.logs.append(root)
        if dic['type'] == 'debug':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('deepskyblue'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('deepskyblue'))
            root.setText(2, '调试')
            root.setForeground(2, QtGui.QColor('deepskyblue'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('deepskyblue'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("deepskyblue"))
        elif dic['type'] == 'info':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('darkgreen'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('darkgreen'))
            root.setText(2, '提示')
            root.setForeground(2, QtGui.QColor('darkgreen'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('darkgreen'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("darkgreen"))
        elif dic['type'] == 'send_message':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('pink'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('pink'))
            root.setText(2, '发送消息')
            root.setForeground(2, QtGui.QColor('pink'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('pink'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("pink"))
        elif dic['type'] == 'send_group_message':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('violet'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('violet'))
            root.setText(2, '发送群消息')
            root.setForeground(2, QtGui.QColor('violet'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('violet'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("violet"))
        elif dic['type'] == 'recv_private_message':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('yellow'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('yellow'))
            root.setText(2, '接受私聊消息')
            root.setForeground(2, QtGui.QColor('yellow'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('yellow'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("yellow"))
        elif dic['type'] == 'recv_group_message':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('lime'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('lime'))
            root.setText(2, '接受群消息')
            root.setForeground(2, QtGui.QColor('lime'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('lime'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("lime"))
        elif dic['type'] == 'error':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('deeppink'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('deeppink'))
            root.setText(2, '一般错误')
            root.setForeground(2, QtGui.QColor('deeppink'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('deeppink'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("deeppink"))
        elif dic['type'] == 'warning':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('red'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('red'))
            root.setText(2, '警告')
            root.setForeground(2, QtGui.QColor('red'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('red'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("red"))
        elif dic['type'] == 'action':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('lightcyan'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('lightcyan'))
            root.setText(2, '动作')
            root.setForeground(2, QtGui.QColor('lightcyan'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('lightcyan'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("lightcyan"))
        elif dic['type'] == 'critical':
            root.setText(0, str(n + 1))
            root.setForeground(0, QtGui.QColor('grey'))
            root.setText(1, time_)
            root.setForeground(1, QtGui.QColor('grey'))
            root.setText(2, '重大错误')
            root.setForeground(2, QtGui.QColor('grey'))
            root.setText(3, dic['sender'])
            root.setForeground(3, QtGui.QColor('grey'))
            root.setText(4, dic['text'])
            root.setForeground(4, QtGui.QColor("grey"))
        self.treeWidget.setCurrentItem(root)

    def addplugin(self, plugin: Plugin):
        n = self.treeWidget_2.topLevelItemCount()
        root = My_tree_item(self.treeWidget_2)
        root.plugin = plugin
        root.setText(0, str(n + 1))
        root.setText(1, str(plugin.enable))
        root.setText(2, plugin.name)
        root.setText(3, plugin.author)
        root.setText(4, str(plugin.ver))
        root.setText(5, plugin.complain)
        self.plugins.append(root)

    def pluginMenu(self, pos):
        menu = QMenu()
        item1 = menu.addAction("启用插件")
        item2 = menu.addAction("禁用插件")
        item3 = menu.addAction("卸载插件")
        item4 = menu.addAction("设置")
        item5 = menu.addAction("添加插件")
        # item5 = menu.addAction("重载插件")
        screenPos = self.treeWidget.mapToGlobal(pos)
        action = menu.exec(screenPos)
        if action == item1:  # 启用插件
            if len(self.treeWidget_2.selectedIndexes()) == 0:
                pass
            else:
                row = self.treeWidget_2.selectedIndexes()[0].row()  # 列
                # print(row)
                plu_name = self.plugins[row]
                plu_name.plugin.enable_func()
                plu_name.plugin.enable = True
                self.plugins[row].setText(1, '启用')
                sql.execute("""update plugin_setting set enable=%s where name='%s'""" % (1, plu_name.plugin.name))
                sql.commit()

        elif action == item2:  # 禁用插件
            if len(self.treeWidget_2.selectedIndexes()) == 0:
                pass
            else:
                row = self.treeWidget_2.selectedIndexes()[0].row()  # 列
                # print(row)
                plu_name = self.plugins[row]
                plu_name.plugin.enable_func()
                plu_name.plugin.enable = False
                self.plugins[row].setText(1, '禁用')
                sql.execute("""update plugin_setting set enable=%s where name='%s'""" % (0, plu_name.plugin.name))
                sql.commit()

                # row = self.treeWidget_2.selectedIndexes()[0]  # 列
                # # plu_name = row.plugin.name
                # row.plugin.is_enable = False
                # row.plugin.disable_func()
                # row.setText(1, '禁用')

        elif action == item3:  # 卸载插件
            if len(self.treeWidget_2.selectedIndexes()) == 0:
                add_Log({'type': 'error', 'sender': '框架', 'text': '请选择一个要卸载的插件'})
            else:
                row = self.treeWidget_2.selectedIndexes()[0].row()  # 列
                # print(row)
                plu_name = self.plugins[row]
                plu_name.plugin.disable_func()
                # row = self.treeWidget_2.selectedIndexes()[0].row()  # 列
                # self.treeWidget_2.takeTopLevelItem(row)
                # plu_name = self.plugins[row].text(2)
                # print(plu_name)
                # os.remove('./plugins/' + plu_name.plugin.name)
                self.plugins[row].setText(1, '已删除')
                sql.delete('plugin_setting', name=plu_name.plugin.name)
                shutil.rmtree('./plugins/' + plu_name.plugin.name)
                del_plugin(plu_name.plugin)
                # os.rmdir('./plugins/' + plu_name.plugin.name)

                # print(1)
            # self.plugins[row].setText(1, '禁用')
            # return

        elif action == item4:  # 设置
            # print('设置')
            if len(self.treeWidget_2.selectedIndexes()) == 0:
                print('pass')
                add_Log({'type': 'error', 'sender': '框架', 'text': '请选择一个要设置的插件'})
            else:
                row = self.treeWidget_2.selectedIndexes()[0].row()  # 列
                # print(row)
                plu_name = self.plugins[row]
                # plu_name.plugin.enable_func()
                threading.Thread(target=plu_name.plugin.setting).start()
                # plu_name = self.plugins[row].text(2)
                # print(plu_name)
                # print(self.plu_dic)

                # print(i)
                # setPlugin(i)
                # print('设置')
                # else:
                #     continue  # 设置
        elif action == item5:
            # print('item5')
            t = threading.Thread(target=add_plugin_with_win, args=(self, sql))
            t.start()
            # add_plugin_with_win()#添加插件

    def show_message(self, s):
        self.ui = Message_detail()
        self.ui.set_text(s)
        self.ui.show_ui()
        # msg_box = QMessageBox.information(self.mainwindow, "消息原文", s,
        #                                   QMessageBox.Yes)  # 最后的Yes表示弹框的按钮显示为Yes，默认按钮显示为OK,不填QMessageBox.Yes即为默认
        # msg_box.exec()


def add_Log(dic: dict):
    ui.addlog(dic)


class TrayIcon(QtWidgets.QSystemTrayIcon):  # 系统托盘类
    def __init__(self, MainWindow, parent=None):
        super(TrayIcon, self).__init__(parent)
        self.ui = MainWindow
        self.createMenu()

    def createMenu(self):
        self.menu = QtWidgets.QMenu()
        self.showAction1 = QtWidgets.QAction("启动", self, triggered=self.show_window)
        self.showAction2 = QtWidgets.QAction("显示通知", self, triggered=self.showMsg)
        self.quitAction = QtWidgets.QAction("退出", self, triggered=self.quit)

        self.menu.addAction(self.showAction1)
        self.menu.addAction(self.showAction2)
        self.menu.addAction(self.quitAction)
        self.setContextMenu(self.menu)

        # 设置图标
        self.setIcon(QtGui.QIcon("./icons/qmiao.png"))
        self.icon = self.MessageIcon()

        # 把鼠标点击图标的信号和槽连接
        self.activated.connect(self.onIconClicked)

    def showMsg(self):
        self.showMessage("Message", "skr at here", self.icon)

    def show_window(self):
        # 若是最小化，则先正常显示窗口，再变为活动窗口（暂时显示在最前面）
        self.ui.showNormal()
        self.ui.activateWindow()

    def quit(self):
        QtWidgets.qApp.quit()

    # 鼠标点击icon传递的信号会带有一个整形的值，1是表示单击右键，2是双击，3是单击左键，4是用鼠标中键点击
    def onIconClicked(self, reason):
        if reason == 2 or reason == 3:
            # self.showMessage("Message", "skr at here", self.icon)
            if self.ui.isMinimized() or not self.ui.isVisible():
                # 若是最小化，则先正常显示窗口，再变为活动窗口（暂时显示在最前面）
                self.ui.showNormal()
                self.ui.activateWindow()
                self.ui.setWindowFlags(QtCore.Qt.Window)
                self.ui.show()
            else:
                # 若不是最小化，则最小化
                self.ui.showMinimized()
                self.ui.setWindowFlags(QtCore.Qt.SplashScreen)
                self.ui.show()
                # self.ui.show()


if __name__ == '__main__':
    QtWidgets.QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(win)
    ti = TrayIcon(win)
    ti.show()
    win.show()
    ui.addlog({'type': 'info', 'sender': '收到消息', 'text': '111'})
    app.exec_()
